### ISSUE TITLE
Run Benchmarks across Node versions

### ISSUE THREAD

**Issue by lukeed** [lukeed/arr#2]
I know, for a fact, that most native built-ins are faster than mine in Node `>=7`. (:tada:)

Should run the full suite (RIP computer) in each Node version & record the results in a clear, concise manner.

Versions:

- [x] 4
- [x] 6
- [x] 7
- [x] 8

**Comment by ForsakenHarmony** [comment]
are they also faster in chrome then?

**Comment by thangngoc89** [comment]
@ForsakenHarmony We need crossbrowser testing suite too to test all JS engine :D

**Comment by lukeed** [comment]
I'm not sure how to set that up // not sure if I _want_ to bother doing it 😅 Benching the different node versions is already a PITA

**Comment by lukeed** [comment]
Closed via 5cb25b2, 344121e, 79a2e0e, and 897b34c 🎉
