### ISSUE TITLE
Contributing each package to Node.js

### ISSUE THREAD

**Issue by paulocoghi** [lukeed/arr#7]
I would like to ask if you could suggest (or if you authorize someone else to suggest) on Node.js community to replace the original array methods to yours.

The difference is clear. :)

**Comment by paulocoghi** [comment]
Sorry, now I realize that you already informed that: `Most functions have slight differences from the native built-ins!`

Maybe, for this reason, they would not be precisely a pure replacement candidate.

**Comment by lukeed** [comment]
The Array methods are built/produced by C++ code, so it couldn't be a drop-in PR or anything. Not by me, anyway

When this repo came out, there was some attention from V8 about it and IIRC it did instigate some performance improvements, I just can't remember which.

As for differences, array holes aren't treated the same and I don't pass in a `this` context to function callers. The latter can be solved easily with ~6B or so, but I don't think either of these behaviors are used very much
